apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: match-data-tenant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/acp-group3273029/alex-container-platform.git
    targetRevision: main
    path: platform/kubernetes/tenants/match-data
  destination:
    server: https://kubernetes.default.svc
    namespace: match-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
