apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: match-data
resources:
  - ../../../base/fixture-service
  - external-secret.yaml
  - service-monitor.yaml
images:
  - name: fixture-service
    newName: registry.gitlab.com/acp-group3273029/alex-container-platform/fixture-service
    newTag: development
patches:
  - target:
      kind: Deployment
      name: fixture-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
