apiVersion: v1
kind: LimitRange
metadata:
  name: container-defaults
  namespace: match-data
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 256Mi
