apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fixture-service-tls
  namespace: match-data
spec:
  secretName: fixture-service-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - fixture-service.match-data.svc.cluster.local
