apiVersion: v1
kind: Secret
metadata:
  name: fixture-service-database
type: Opaque
stringData:
  url: postgresql://matchops:matchops@fixture-service-postgres:5432/matchops
  username: matchops
  password: matchops
