apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fixture-service-database
  namespace: match-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-secret-store
  target:
    name: fixture-service-database
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: fixture-service-database
        property: url
    - secretKey: username
      remoteRef:
        key: fixture-service-database
        property: username
    - secretKey: password
      remoteRef:
        key: fixture-service-database
        property: password
