apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: match-data
resources:
  - ../../../base/fixture-service
  - external-secret.yaml
  - postgres.yaml
  - certificate.yaml
  - ingress.yaml
images:
  - name: fixture-service
    newName: fixture-service
    newTag: local
patches:
  - target:
      kind: Deployment
      name: fixture-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/initContainers
        value:
          - name: migrate
            image: fixture-service:local
            imagePullPolicy: Never
            command: ["npm", "run", "migrate"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: fixture-service-database
                    key: url
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
  - target:
      kind: Deployment
      name: fixture-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
