apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: results-service-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: results-service-database
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: match-data/development/results-service
        property: databaseUrl
